name: refreshable_widget
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/Yama-Roni/refreshable-widget

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
