name: any_refreshable_widget
description: A powerful Flutter package providing pull-to-refresh functionality for any widget, with support for single/multiple futures, custom indicators, and comprehensive error handling.
version: 0.0.2
homepage: https://github.com/Yama-Roni/any_refreshable_widget
repository: https://github.com/Yama-Roni/any_refreshable_widget
issue_tracker: https://github.com/Yama-Roni/any_refreshable_widget/issues
documentation: https://github.com/Yama-Roni/any_refreshable_widget#readme

topics:
  - flutter
  - widget
  - refresh
  - pull-to-refresh
  - ui

platforms:
  android:
  ios:

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Screenshots for pub.dev
screenshots:
  - description: 'AnyRefreshableWidget demo showing pull-to-refresh functionality'
    path: snapshot/example.gif
